[package]
name = "configman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capturing-glob = "0.1.1"
git2 = "0.15.0"
